module.exports = {
    queues: (searchTerm) => {
        return {
            '0': 'Custom',
            '72': 'Snowdown Showdown',
            '73': 'Snowdown Showdown',
            '75': 'Hexakill',
            '76': 'Ultra Rapid Fire',
            '78': 'One For All: Mirror Mode',
            '83': 'Co-op vs AI Ultra Rapid Fire',
            '98': 'Hexakill',
            '100': 'ARAM',
            '310': 'Nemesis',
            '313': 'Black Market Brawlers',
            '317': 'Definitely Not Dominion',
            '325': 'All Random',
            '400': 'Normal Draft Pick',
            '420': 'Ranked Solo',
            '430': 'Blind Pick',
            '440': 'Ranked 5x5 Flex',
            '450': 'ARAM',
            '460': 'Normal 3v3',
            '470': 'Ranked 3v3 Flex',
            '600': 'Blood Hunt Assassin',
            '610': 'Dark Star: Singularity',
            '700': 'Clash',
            '800': 'Co-op vs. AI Intermediate',
            '810': 'Co-op vs. AI Intro',
            '820': 'Co-op vs. AI Beginner',
            '830': 'Co-op vs. AI Intro',
            '840': 'Co-op vs. AI Beginner',
            '850': 'Co-op vs. AI Intermediate',
            '900': 'ARURF',
            '910': 'Ascension',
            '920': 'Legend of the Poro King',
            '940': 'Nexus Siege',
            '950': 'Doom Bots Voting',
            '960': 'Doom Bots Standard',
            '980': 'Star Guardian Invasion: Normal',
            '990': 'Star Guardian Invasion: Onslaught',
            '1000': 'PROJECT: Hunters',
            '1010': 'Snow ARURF',
            '1020': 'One for All',
            '1030': 'Odyssey Extraction: Intro',
            '1040': 'Odyssey Extraction: Cadet',
            '1050': 'Odyssey Extraction: Crewmember',
            '1060': 'Odyssey Extraction: Captain',
            '1070': 'Odyssey Extraction: Onslaught',
            '1090': 'Teamfight Tactics',
            '1100': 'Ranked Teamfight Tactics'
        } [searchTerm];
    },
    maps: (searchTerm) => {
        return {
            '1': 'Summoner\'s Rift',
            '2': 'Summoner\'s Rift',
            '3': 'The Proving Grounds',
            '4': 'Twisted Treeline',
            '8': 'The Crystal Scar',
            '10': 'Twisted Treeline',
            '11': 'Summoner\'s Rift',
            '12': 'Howling Abyss',
            '14': 'Butcher\'s Bridge',
            '16': 'Cosmic Ruins',
            '18': 'Valoran City Park',
            '19': 'Substructure 43',
            '20': 'Crash Site',
            '21': 'Nexus Blitz',
        } [searchTerm];
    }
}